"""add icon to application and department

Revision ID: 22eb22221ce3
Revises: 2000f660380c
Create Date: 2015-10-13 16:14:25.405559

"""

# revision identifiers, used by Alembic.
revision = '22eb12311ce3'
down_revision = '1233f660380c'
branch_labels = None
depends_on = None

from alembic import op
from alembic import context
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # We need to create the enum first otherwise SQLAlchemy complains about it
    # not existing and the migration fails
    icon_types = sa.Enum('finance', 'human-resources', 'logistics', 'call-centre', 'web-store', 'operations', 'it', name='icons')
    check = False if context.is_offline_mode() else True
    icon_types.create(op.get_bind(), checkfirst=check)

    op.add_column('applications', sa.Column('icon', icon_types))
    op.add_column('departments', sa.Column('icon', icon_types))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'icon')
    op.drop_column('applications', 'icon')
    ### end Alembic commands ###
